name: List Files and Print Working Directory on Self-Hosted Runner

on:
  push:
    branches:
      - branch
 

jobs:
  test-job:
    runs-on: [self-hosted]  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: 'branch1'

    - name: Print Current Directory (pwd) and List Files (ls
      run: |
        echo "Current directory:"
        pwd 
        echo "Listing files in the current directory:"
        ls -l 


        name: Self-Hosted Runner Hello World
