name: Deploy on Commit

on:
  push:
    branches:
      - main  
  deploy:
    runs-on: self-hosted  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Make script deploy executable
        run: chmod +x /Users/hemanth.k/Documents/try.sh  

      - name: execute shell script
        run: /Users/hemanth.k/Documents/try.sh  
