name: Self-Hosted Runner Hello World

on:
  push:
    branches:
      - main

jobs:
  hello-hemanth:
    runs-on: self-hosted

    steps:
      - name: Checkout Codes
        uses: actions/checkout@v2

      - name: Display Hello heamnth
        run: echo "Hello, Hemanth!"
