name: Self-Hosted Runner Hello World

on:
  push:
    branches:
      - main

jobs:
  hello-hem:
    runs-on: self-hosted

    steps:
      - name: Checkout Codes0
        uses: actions/checkout@v2

      - name: Display Hello World
        run: echo "Hello, World!"
